import { StyleSheet, Dimensions } from "react-native";

const { height: SCREEN_H } = Dimensions.get("window");

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  bg: { flex: 1 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: SCREEN_H,
    paddingHorizontal: 24,
    paddingTop: 64,
    paddingBottom: 28,
  },
  topSection: {
    alignItems: "center",
  },
  middleSection: {
    flex: 1,
    justifyContent: "center",
  },
  logoBox: {
    width: 68,
    height: 68,
    borderRadius: 18,
    backgroundColor: "rgba(37, 99, 235, 0.9)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  title: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "700",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  subtitle: {
    color: "#E2E8F0",
    fontSize: 14,
    marginTop: 4,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  label: { fontSize: 13, fontWeight: "600", color: "#374151", marginBottom: 6 },
  passwordHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
  },
  forgotText: { fontSize: 13, color: "#2563EB", fontWeight: "500" },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 48,
    backgroundColor: "#F9FAFB",
  },
  inputIcon: { marginRight: 8 },
  input: { flex: 1, fontSize: 15, color: "#111827" },
  errorText: { color: "#DC2626", fontSize: 13, marginTop: 10 },
  loginButton: {
    flexDirection: "row",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    gap: 8,
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonDisabled: { opacity: 0.7 },
  loginButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  footerText: {
    color: "#E2E8F0",
    fontSize: 11,
    textAlign: "center",
    marginTop: 8,
  },
});