import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F9FAFB" },
  pageTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  mutedText: {
    color: "#6B7280",
    fontSize: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  dateText: { fontSize: 15, fontWeight: "700", color: "#111827" },
  todayBadge: {
    fontSize: 11,
    fontWeight: "600",
    color: "#2563EB",
    marginTop: 2,
  },
  emptyState: {
    marginHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 64,
  },
  emptyIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyText: { color: "#6B7280", fontSize: 14, textAlign: "center" },
  errorBanner: {
    marginHorizontal: 16,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  errorBannerText: { color: "#DC2626", fontSize: 14, flex: 1 },
  banner: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
  },
  bannerAmber: { backgroundColor: "#FFFBEB", borderColor: "#FDE68A" },
  bannerBlue: { backgroundColor: "#EFF6FF", borderColor: "#BFDBFE" },
  bannerGray: { backgroundColor: "#F3F4F6", borderColor: "#E5E7EB" },
  bannerText: { fontSize: 14, fontWeight: "500", marginLeft: 8, flex: 1 },
  markAllRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  dot: { width: 6, height: 6, borderRadius: 3, marginRight: 5 },
  chipText: { fontSize: 12, fontWeight: "600" },
  countText: { fontSize: 12, fontWeight: "600", color: "#9CA3AF" },
  rosterCard: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    overflow: "hidden",
  },
  rowSeparator: {
    height: 1,
    backgroundColor: "#F3F4F6",
    marginHorizontal: 16,
  },
  saveButton: {
    backgroundColor: "#2563EB",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 8,
  },
});
