import { InvoiceArray } from '@/src/types/fees';

const now = new Date();
const feeStructureBase = {
  id: 'fs1',
  sectionId: 'sec1',
  academicYearId: 'ay1',
  tuitionFee: 25000,
  examFee: 1500,
  transportFee: 4000,
  hostelFee: 0,
  otherFee: 500,
  createdAt: now,
  updatedAt: now,
};

export const dummyInvoices: InvoiceArray = [
  {
    id: 'inv1',
    studentId: 's1',
    feeStructureId: 'fs1',
    totalAmount: 31000,
    paidAmount: 31000,
    status: 'Paid',
    dueDate: new Date('2026-06-15'),
    description: 'Term 1 Fees',
    createdAt: now,
    updatedAt: now,
    feeStructure: feeStructureBase,
    payments: [
      {
        id: 'pay1',
        invoiceId: 'inv1',
        studentId: 's1',
        amount: 31000,
        method: 'RAZORPAY',
        status: 'Success',
        reference: null,
        razorpayOrderId: 'order_abc123',
        razorpayPaymentId: 'pay_abc123',
        paidAt: new Date('2026-06-10'),
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
  {
    id: 'inv2',
    studentId: 's1',
    feeStructureId: 'fs1',
    totalAmount: 31000,
    paidAmount: 15000,
    status: 'Partial',
    dueDate: new Date('2026-08-10'),
    description: 'Term 2 Fees',
    createdAt: now,
    updatedAt: now,
    feeStructure: feeStructureBase,
    payments: [
      {
        id: 'pay2',
        invoiceId: 'inv2',
        studentId: 's1',
        amount: 15000,
        method: 'RAZORPAY',
        status: 'Success',
        reference: null,
        razorpayOrderId: 'order_def456',
        razorpayPaymentId: 'pay_def456',
        paidAt: new Date('2026-07-05'),
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
  {
    id: 'inv3',
    studentId: 's1',
    feeStructureId: 'fs1',
    totalAmount: 31000,
    paidAmount: 0,
    status: 'Pending',
    dueDate: new Date('2026-07-01'), // in the past relative to "today" — overdue
    description: 'Term 3 Fees',
    createdAt: now,
    updatedAt: now,
    feeStructure: feeStructureBase,
    payments: [],
  },
];